### ISSUE TITLE
[todaypost] 오늘의 게시글 스크립트 완성하기

### ISSUE THREAD

**Issue by rkskekzzz** [rkskekzzz/80000coding_notion_api#2]
# TODO

- [ ] 노션에 오늘의 게시글 checkbox 생성해두기
- [ ] 오늘의 게시글 id dump 최신화하기
- [ ] 역대 오늘의 게시글 checkbox 체크해주는 스크립트 작성하기
